---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Setup hostfile
  copy:
    src: "{{ role_path }}/files/hosts"
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: Install Java
  yum:
    name: 'java-1.8.0-openjdk'
    state: latest
