---
# Install mesos dependencies
# https://open.mesosphere.com/advanced-course/installing-software/
- name: Install mesosphere
  yum:
    name: http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
  ignore_errors: true

- name: Install mesos
  yum:
    name: mesos
    state: latest

- name: Install marathon
  yum:
    name: marathon
    state: latest

- name: Configure marathon
  copy:
    src: "{{ role_path }}/files/marathon.conf"
    dest: /etc/default/marathon
    owner: root
    group: root
    mode: 0644

- name: Start mesos-master
  service:
    name: mesos-master
    state: started
    enabled: yes

- name: Start mesos-slave
  service:
    name: mesos-slave
    state: started
    enabled: yes

- name: Start marathon
  service:
    name: marathon
    state: started
    enabled: yes  
