---
# Install marathon
# https://open.mesosphere.com/advanced-course/using-apache-mesos/
# https://open.mesosphere.com/advanced-course/starting-marathon/
- name: Install marathon
  yum:
    name: marathon
    state: latest

- name: Configure marathon
  copy:
    src: "{{ role_path }}/files/marathon.conf"
    dest: /etc/default/marathon
    owner: root
    group: root
    mode: 0644

- name: Start marathon
  service:
    name: marathon
    state: started
    enabled: yes  
