---
- name: Apply all available patches
  hosts: all
  become: true
  roles:
    - base

- name: Install Mesos, Marathon, Zookeeper
  hosts: all
  become: true
  roles:
    - mesos
    - marathon
    - zookeeper
    - mesos-dns
  environment:
    GOPATH: "/opt/golang"
    PATH: "{{ ansible_env.PATH }}:/opt/golang/bin"
